### ISSUE TITLE
The use of unseen labels during the training!

### ISSUE THREAD

**Issue by fshamshirdar** [valeoai/zero_shot_semantic_segmentation#1]
Hi there,
I have read your paper and the code, brilliant idea. I have a few questions on the implementation:
1. Are unseen target labels being used for training the classifier? (Line 264 train_context_GMMN.py). If so, how is this method different than just training the backbone - deeplabv3+ using (seen and unseen) target labels.
2. For fine-tuning the classifier to predict unseen label, how would you place and arrange the unseen generated visual features so that the classifier can exploit the spatial correlation between visual features? Could you please elaborate on the fine tuning procedure of the classifier?
3. GCN is taking in the graph that is being generated based on the seen and unseen labels. Aren’t we supposed not to use any information on the unseen labels during the training process for ZSL.

**Comment by maximebucher** [comment]
Hello @fshamshirdar,

1. Unseen labels and semantic embedding are used for the generation of synthetic visual features only, training images of unseen classes are not accessible. it differ from "just training the backbone - deeplabv3+" that needs full supervision (images of unseen classes and label maps).

2. Similar to DeepLabv3+, the classification layer consists of a 1x1convolutional layer. The final classifier do not exploit spatial correlation between visual features because it operates on individual pixel-wise features. 

3. Using segmentation masks for GCN does not amount to full supervision for the unseen classes since images themselves are not accessible. Indeed, the way we design this graph is in fact very loose, requiring only relative spatial arrangements, not object shapes. Using segmentation masks is only one possible strategy, which we chose for the sake of convenience. However, any other, less precise contextual descriptions of unseen objects would suffice to build useful graphs.  

Maxime

**Comment by fshamshirdar** [comment]
Hi Maxime,

Thanks for your reply.
1 and 3: I understand your points, but isn’t it like you trained your classifier indirectly using another model that tries to match its prob distribution with the backbone? Generator has access to the unseen labels and their location (which could exploit their spatial correlation). Let me put it this way: are you able to train the model with any unseen labels that are not in the dataset? (e.g dog which is not in cityscapes). From my understanding, we can assume that if you pass any word from w2v to the generator (putting the graph aside) it may provide the same distribution that the backbone provides for the actual pixels of a dog, this assumption however depends a lot on the number of seen labels we have, DeVISE employed 1000 words to model the transformation, cityscapes has no more than 30.

**Comment by maximebucher** [comment]
Hello Faraz, 

sorry for the late reply.

(1) During training no spatial information is given to the generator, it is trained by batch of feature of the same class. The process of feature generation for unseen classes is done by using their semantic representation only. (3) Graph context does not use complete pixel supervision but only the adjacency information.

I hope these answers help you!

Maxime
